// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActives() {
  return window['go']['main']['App']['GetActives']();
}

export function GetNavs() {
  return window['go']['main']['App']['GetNavs']();
}

export function GetReps() {
  return window['go']['main']['App']['GetReps']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}
