// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {nav} from '../models';

export function GetActives():Promise<Array<types.ActivityItem>>;

export function GetNavs():Promise<Array<nav.NavItems>>;

export function GetReps():Promise<Array<types.RepoItem>>;

export function GetStats():Promise<Array<types.StatsCard>>;
